### ISSUE TITLE
Incompatible with hardware throttle

### ISSUE THREAD

**Issue by mcoindeau** [Huertix/dcs-throttle#1]
Throttle value override any change done by any other controller

**Comment by Huertix** [comment]
Hi Mika.

You mean it is not possible tu use a external throttle device with flaps and air brake switchs, isn't it?

**Comment by mcoindeau** [comment]
Hi,
Here's my issue. I wanted to use the app only for the flaps and ab switch and status.
I used the in-app throttle slider, and then switched back to my joystick, moving the hardware throtlle slider and the in-game throttle always go back to the application value.
