### ISSUE TITLE
how do you know what argument_value to use?

### ISSUE THREAD

**Issue by steveh2112** [Huertix/dcs-throttle#2]
hi, thanks for posting this, i'd like to read thrust, and saw your code

local engine_thr_left_now = MainPanel:get_argument_value(8) \* 100 --F86(104), Mig15(205)

how do you know what argument value to use for any given plane?

thx steve

**Comment by Huertix** [comment]
Hi long time I didn't review this code! Let me check it and I'll back to you soon! ;)

**Comment by steveh2112** [comment]
actually MainPanel:get_argument_value(anything) doesn't work on the SU-27, maybe its just an a10c thing?

**Comment by Huertix** [comment]
Could be!  This would be my next step in this app, but I did not have too much time. I did not find too much info about how to get the info from others aircraft, and the info I've found was old and for previous versions of DCS.
